language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
before_install:
- openssl aes-256-cbc -K $encrypted_456304804b07_key -iv $encrypted_456304804b07_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: ccc7giOrdL1AaSysyjExc4UMuMoZmZk1t0OPOWJ9efZyVB+pgcXFfixpnm3AwDTF3hZEt8t5tYtdJJZtAXlx2PXX5QrqwpbuF6DosUoRrdDAJ8yj1TsyUxvm1eXdrPghud5ncf1Zya3dqEUM4vT7/aOiLwqCg0nYb+Cr7Iq0rMl9y87da3kCXW1Fid89T7wDsUdx4CFlpotsCerechcS8ShFzgKqdsyKK8Rpk5obcMDkbq8h6/LX9ODPZttPTmLLiA4YiemY4WlDoOiE2h0fEySJalEIU8mgtj3G8q5doy8E9+kVPKgRMo7Rb/geeKsEEpxXt7300KlFdCDJtF1f2oVaOdMSgJBuKb24qthEe3khruKZ2jno6uTeEJXd7J5hqkP89FuPZT5rolpgVzjGo1eLOBavMiVWdIcqutIL5ogrvjuejS+WXda8lUGoM5cN4yDiuqSVnL64PpWleZDz/+uyEXHPvysyI9ZBG3duPbkI6z0fz+3iLFKOKBxh23+hUGk+y8TnLEOPR4MLhL7/qwBax6C7BcVxJqyVqKsqJ35ZKWmlJvTuZzon54umOG9UcSuvG5qUuwxINrrNxG0Uq8FRwnSUoD1GFsKaviUIgN3GUdUlU4/xEfoYcTlodPmTsSP66vwHD0EVYRCCuEJTbx5rEZEc3OBRKXQpLHBfzgA=
  - secure: MTbJQLZ7RmUYuau5ZIipXVryv+QdpUGOn/Uvyj1BUGK2iKMVfjNLQfQH+Ei///IcCiIPbGxRTtN+vHmHNNJxrk+Yw4UMLVhoffdMjlm+YMGCoZv0H4SSB4oT8D6njOvOjwnxFh8nTwTZY9PMgXlu6tKtLGIoie1gSV05OiNuZJGfwsdY0zfwDKFZos8wJd+wPU4YtNe6WPfASVfgF9yfMYXoAtdGCZ/RHwrGTEePAUuhrRyL3ZBT0BjMlQeYoIlfBgR6xGN+HGQYFlWSQHOQJe7f+w/oFclMRABmCeeMJu9dbdwYL0kmItwRCyp7GVJP6FfAJDXxbej/sfHtAdFoVPmoZToW32pNaezDEa4NnKvnoNx1PRatD2mECUbtWx7k5LNCOWB4ZxG76Cxlv2rhbUgXHnFOyVNdAxVP/e+abKhiotld+RDbaoNBv2PuDG0vBc1OVxoNAp5e87D54c+fq9RlsmcmqO1FHDg2MEC0PPYUQ/368ZnaBYD4J76Pyl4Hw+n0wWUb+8n/J6M9+g3q76z95NcuIesE7CA0s9edIEs4mu10fJb61wp4dhO7D0IFk+G+FxtIJjTT8CpAt4JW6qpOcBZ8V4VrN6oDkG1+azgRR7MJreCv3nSBJI1DM7RM80FL6EJ74igQFcqvJG7l3t6bRMXqmHUGS7CYfa2SpAE=
  - secure: vyHLdY8mLxgSbB57oYieyqvjN0fCQhmN1A44NVEZjY5Wz0Vilmt5tCeI+dPFrI7rguJoeDh+IQ/7sWtJM7tpKNlUEFp2AQye7huQ+kPSGcCO9ZyjvG4liyj9A4J32Y/afHYSj5EllHOs0PXyro6fdH89U+t2EWbPD2PtCbAH3Ks7BfZUBZSAj0gxNVuuBNQGIiFYeW1CgHp8MSaNVeWDzJnHug8DUH4ovd396bwtwwk+icw8gtGnQBtXB++kEWZSqsiCSHgG4PKDy7yuKQMq9a2InHJzx3/aOOTBk9VxFuCgppNpN8gqAM3yjP3UFlz5S6wBTbBAEGBZxaadih8FCx1cXgXf3CSp/D53dE9rcZ/obbujSuOnmP0urY7jJ+/o7Ma3cg0KFe1O1M5VsHxp2PHSy7zgwzPBJABdqfXBgjwDeXKgTc2crRfGQ5iysd/QK3vlA/TdK/ks4HJ6LSfKHjFagtrGdcjgZRyMRgDURcpJL1DVV75wDrNdiU2SnWtVS3V3m5tLlIdzNEXQzC2jBVNpRDK9JQU5q8K3N+y3lC+YV6PBx+L9kVwNR5bF14l8m/YOLHg95X9FJIe3JaS1GB1CMQOaeLGxhKU97XLp8oP+AOv+UYyqpwpcV4ZlcliHS5+nHjsgbZrLpxILXKUk1J316yQEvNzZ+B9s7jlgfuQ=
